using System.Globalization;
using System.Text;
using CostEstimationCli.Models;

namespace CostEstimationCli.Services;

/// <summary>
/// Generates a Markdown cost-estimate summary suitable for posting as a
/// pull-request comment or storing as a CI/CD artefact.
/// </summary>
public class MarkdownReportGenerator
{
    private static readonly CultureInfo UsCulture = new("en-US");

    /// <summary>
    /// Produces a complete Markdown report string from the supplied estimate.
    /// </summary>
    /// <param name="estimate">Full cost estimate returned by the API.</param>
    /// <param name="budget">Optional monthly budget limit used for the status indicator.</param>
    public string Generate(CostEstimateResponseModel estimate, decimal? budget)
    {
        var delta        = estimate.Delta;
        var monthlyCost  = estimate.aggregateCosts.PerMonth;
        var budgetLimit  = budget;
        var exceeded     = budgetLimit.HasValue && monthlyCost > budgetLimit.Value;

        var statusEmoji  = exceeded ? "❌ Budget Exceeded!" : "✅ Within Budget";

        var sb = new StringBuilder();

        // ── Headline ──────────────────────────────────────────────────────────
        sb.AppendLine($"## 💰 Cost Estimate Summary: {statusEmoji}");
        sb.AppendLine();

        // ── Summary table ─────────────────────────────────────────────────────
        sb.AppendLine("| Timeframe | Calculated Cost | Budget Limit | Status |");
        sb.AppendLine("|-----------|-----------------|--------------|--------|");

        var budgetCell  = budgetLimit.HasValue ? Usd(budgetLimit.Value) : "—";
        var statusCell  = exceeded ? "❌ Exceeded" : "✅ OK";
        sb.AppendLine($"| Monthly | {Usd(monthlyCost)} | {budgetCell} | {statusCell} |");
        sb.AppendLine();

        // ── Delta / net change ────────────────────────────────────────────────
        if (delta is not null)
        {
            var sign       = delta.NetMonthly >= 0 ? "+" : "";
            var netFormatted = $"{sign}{Usd(delta.NetMonthly)}";
            var opSummary  = BuildOpSummary(delta);

            sb.AppendLine($"**Net Change:** `{netFormatted} / month`");
            sb.AppendLine();
            sb.AppendLine($"> {opSummary}");
            sb.AppendLine();
        }

        // ── Expandable resource breakdown ─────────────────────────────────────
        sb.AppendLine("<details>");
        sb.AppendLine("<summary>🔍 View Resource Breakdown</summary>");
        sb.AppendLine();

        AppendResourceBreakdown(sb, estimate);

        sb.AppendLine("</details>");
        sb.AppendLine();

        // ── Unsupported resources note ────────────────────────────────────────
        if (estimate.unsupportedResources?.Count > 0)
        {
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine($"> ⚠️ **{estimate.unsupportedResources.Count} resource(s)** could not be estimated "
                        + "(unsupported type). See CLI output for details.");
            sb.AppendLine();
        }

        // ── Footer ────────────────────────────────────────────────────────────
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("_Generated by [Cloudcostify](https://cloudcostify.io) · "
                    + $"Prices in {(string.IsNullOrWhiteSpace(estimate.currency) ? "USD" : estimate.currency.ToUpperInvariant())}_");

        return sb.ToString();
    }

    // ── Resource breakdown helpers ─────────────────────────────────────────────

    private static void AppendResourceBreakdown(StringBuilder sb, CostEstimateResponseModel estimate)
    {
        if (estimate.cloudResources is null || estimate.cloudResources.Count == 0)
        {
            sb.AppendLine("_No priced resources found._");
            sb.AppendLine();
            return;
        }

        var allClusters  = estimate.cloudResources.SelectMany(r => r.aksManagedClusters ?? []).ToList();
        var allVms       = estimate.cloudResources.SelectMany(r => r.virtualMachines ?? []).ToList();
        var allVmssList  = estimate.cloudResources.SelectMany(r => r.virtualMachineScaleSets ?? []).ToList();
        var allDbs       = estimate.cloudResources.SelectMany(r => r.sqlDatabases ?? []).ToList();
        var allMis       = estimate.cloudResources.SelectMany(r => r.sqlManagedInstances ?? []).ToList();

        if (allClusters.Count > 0)
        {
            sb.AppendLine("### 🖥️ AKS Managed Clusters");
            sb.AppendLine();
            sb.AppendLine("| Name | Location | Resource Group | Tier | Monthly Cost |");
            sb.AppendLine("|------|----------|---------------|------|--------------|");
            foreach (var c in allClusters)
            {
                sb.AppendLine(
                    $"| {Escape(c.name)} | {Escape(c.location)} | {Escape(c.resourceGroupName)} "
                  + $"| {Escape(c.tier)} | {Usd(c.aggregateAKSClusterCosts.PerMonth)} |");
            }
            sb.AppendLine();
        }

        if (allVms.Count > 0)
        {
            sb.AppendLine("### 💻 Virtual Machines");
            sb.AppendLine();
            sb.AppendLine("| Name | Location | SKU | OS | Monthly Cost |");
            sb.AppendLine("|------|----------|-----|----|--------------|");
            foreach (var v in allVms)
            {
                sb.AppendLine(
                    $"| {Escape(v.name)} | {Escape(v.location)} | {Escape(v.virtualMachineSku.sku)} "
                  + $"| {Escape(v.operatingSystem)} | {Usd(v.aggregateVirtualMachineCosts.PerMonth)} |");
            }
            sb.AppendLine();
        }

        if (allVmssList.Count > 0)
        {
            sb.AppendLine("### 🖥️ VM Scale Sets");
            sb.AppendLine();
            sb.AppendLine("| Name | Location | SKU | Instances | Monthly Cost |");
            sb.AppendLine("|------|----------|-----|-----------|--------------|");
            foreach (var s in allVmssList)
            {
                sb.AppendLine(
                    $"| {Escape(s.name)} | {Escape(s.location)} | {Escape(s.virtualMachineSku.sku)} "
                  + $"| {s.instanceCount} | {Usd(s.aggregateVirtualMachineScaleSetCosts.PerMonth)} |");
            }
            sb.AppendLine();
        }

        if (allDbs.Count > 0)
        {
            sb.AppendLine("### 🗄️ SQL Databases");
            sb.AppendLine();
            sb.AppendLine("| Name | Location | SKU | Tier | Monthly Cost |");
            sb.AppendLine("|------|----------|-----|------|--------------|");
            foreach (var d in allDbs)
            {
                sb.AppendLine(
                    $"| {Escape(d.name)} | {Escape(d.location)} | {Escape(d.sqlDatabaseSku.sku)} "
                  + $"| {Escape(d.sqlDatabaseSku.tier)} | {Usd(d.aggregateSqlDatabaseCosts.PerMonth)} |");
            }
            sb.AppendLine();
        }

        if (allMis.Count > 0)
        {
            sb.AppendLine("### 🗄️ SQL Managed Instances");
            sb.AppendLine();
            sb.AppendLine("| Name | Location | SKU | vCores | Monthly Cost |");
            sb.AppendLine("|------|----------|-----|--------|--------------|");
            foreach (var m in allMis)
            {
                sb.AppendLine(
                    $"| {Escape(m.name)} | {Escape(m.location)} | {Escape(m.sqlManagedInstanceSku.sku)} "
                  + $"| {m.sqlManagedInstanceSku.vCores} | {Usd(m.aggregateSqlManagedInstanceCosts.PerMonth)} |");
            }
            sb.AppendLine();
        }
    }

    private static string BuildOpSummary(CostDelta delta)
    {
        var parts = new List<string>();
        if (delta.CreatedCount   > 0) parts.Add($"**{delta.CreatedCount}** created");
        if (delta.DeletedCount   > 0) parts.Add($"**{delta.DeletedCount}** deleted");
        if (delta.UpdatedCount   > 0) parts.Add($"**{delta.UpdatedCount}** updated");
        if (delta.UnchangedCount > 0) parts.Add($"**{delta.UnchangedCount}** unchanged");

        return parts.Count > 0
            ? string.Join(", ", parts) + " resource(s)"
            : "No resource changes detected";
    }

    private static string Usd(decimal amount) =>
        $"${amount.ToString("N2", UsCulture)}";

    /// <summary>Escapes Markdown pipe characters inside table cell values.</summary>
    private static string Escape(string? value) =>
        (value ?? "—").Replace("|", "\\|");
}
